[project]
name = "mcpserver-weather"
version = "0.1.0"
description = "Accesses weather alerts from the US National Weather Service"
requires-python = ">=3.14"
dependencies = [
    "dotenv==0.9.9",
    "requests==2.32.5",
    "pytest>=9.0.2",
    "pyyaml",
]
